name: Build and release
## https://docs.github.com/en/actions/learn-github-actions/variables#default-environment-variables

on:
  push:
    branches: master
    paths-ignore:
    - '.github/**'        # Ignore changes towards the .github directory
    - '**.md'             # Do no build if *.md files changes
    - 'docs/**'
    - 'tools/**'
  #push:
  #  tags:
  #    - "v*.*.*"
  workflow_dispatch:

jobs:
  build_firmware:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio
      - name: Checkout Workspace DIR
        run: echo "Workspace:${{ github.workspace }}"
      - name: Build PlatformIO Project
        run: pio run -d "./HCPBridgeESP32"

      #- name: Show dirs
      #  run: |
      #    find .
      #    find . -type f -name "*.bin"
      #    find . -type d -name fw

      # upload Release:
      - name: Get current date
        id: date
        run: echo "DATE=$(date +%Y.%m.%d)" >> $GITHUB_OUTPUT
      - name: Release
        uses: softprops/action-gh-release@v2
        #if: startsWith(github.ref, 'refs/tags/')
        with:
          name: ${{ steps.date.outputs.DATE }}
          tag_name: ${{ steps.date.outputs.DATE }}
          #token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
          generate_release_notes: true
          make_latest: true
          files: |
            ./HCPBridgeESP32/fw/*.bin